version: '3'
services:
  online-cinema.api:
    image: ghcr.io/itsaln/open-ai-api/open-ai:develop
    container_name: open-ai
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./.env:/opt/app/.env